### ISSUE TITLE
Segfault if you unzip rom

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-fceumm#15]
If you try to open rom using the unzip feature of RA, it segfaults. You can open normally if you don't unzip and choose fceumm core.

```
RetroArch: rarch_log_libretro: [libretro INFO] :: Loading /home/odroid/Games/NES/DuckTales (USA).zip#DuckTales (USA).nes...

RetroArch [WARN] :: rarch_log_libretro :: [libretro WARN] :: Error opening "/home/odroid/Games/NES/DuckTales (USA).zip#DuckTales (USA).nes"!RetroArch [ERROR] :: load_content :: Failed to load content.

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt full
Cannot access memory at address 0x4
#0  0x00000000 in ?? ()
No symbol table info available.
#1  0x0004efa0 in ?? ()
No symbol table info available.
Cannot access memory at address 0x4
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by Alcaro** [comment]
Unzipping is a frontend feature. Raise this on RetroArch.
